name: ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: add-apt-repository ppa:canonical-chromium-builds/stage
    - run: apt update
    - run: apt install chromium-browser
    - run: apt install chromium-codecs-ffmpeg-extra
    - run: npm install
    - run: npm test
      env:
        CI: true
